# This yml file to run Reminder.py script
---
name: run python script for reminde me on telegram

on:
  schedule:
    - cron: "*/5 * * * *"

    # This command allows us to run the Action automatically from the Actions tab.
  #workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify your Python version

      - name: Install Dependencies
        run: pip install -r .github/scripts/requirements.txt

      - name: Run Python Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.K7413D_REMINDER_BOT_TOKEN }} #Get the bot token from Secret
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }} #Get the user ID from Secret
        run: python .github/scripts/Reminder.py
