# this yml file to run Sendinfo.py to send commit hash to me on telegram
---
name: Run Python Script with Commit hash code

on:
  push: # spacify the trigger on push
    branches:
      - main # spacify the main branch only

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Specify your Python version

      - name: Install Dependencies
        run: pip install pyTelegramBotAPI

      - name: export the Url to Github env
        run: |
          TMP="${{ github.repositoryUrl }}"
          TMP="${TMP/git:\/\//https:\/\/}"
          echo "res=$TMP" >> $GITHUB_ENV

      - name: Run Python Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} #Get the bot token from Secret
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }} #Get the user ID from Secret
        run: python .github/scripts/SendInfo.py ${{ env.res }}